webtalk_init -webtalk_dir E:/study/Computer System/Single_cycle_CPU/Single_cycle_CPU.sim/sim_1/behav/xsim/xsim.dir/mycpu_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jun 25 09:58:20 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ea3133f1-0a1e-4b62-b55b-c2cb024f1a13" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e458b8af1ed54d7f865f871cb32565ae" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "36" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "200664798 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.31_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9588_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3767561213 -regid "" -xml E:/study/Computer System/Single_cycle_CPU/Single_cycle_CPU.sim/sim_1/behav/xsim/xsim.dir/mycpu_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/study/Computer System/Single_cycle_CPU/Single_cycle_CPU.sim/sim_1/behav/xsim/xsim.dir/mycpu_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/study/Computer System/Single_cycle_CPU/Single_cycle_CPU.sim/sim_1/behav/xsim/xsim.dir/mycpu_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
